### ISSUE TITLE
'DiGraph' object has no attribute 'node' when using net.draw()

### ISSUE THREAD

**Issue by kaisengit** [kirichoi/netplotlib#33]
Hi there. I installed netplotlib inside my existing conda tellurium environment. I know that libroadrunner already supports r.draw() but the examples from netplotlib do look nicer. 
Anyway, when trying the provided sample in jupyerlab

```
AntimonyStr = '''
$Xi -> S1; k0*Xi
S1 -> S2; k1*S1
S2 -> S3; k2*S2
S1 -> S3; k3*S1
S3 -> $Xo; k4*S3

Xi = 3; Xo = 2
k0 = 0.46; k1 = 0.73; k2 = 0.64;
k3 = 0.51; k4 = 0.22
'''
net = npl.Network(AntimonyStr)
net.draw()
```

I get the following error:
> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-22-59411b3f60b4> in <module>
>      11 '''
>      12 net = npl.Network(AntimonyStr)
> ---> 13 net.draw()
> 
> /opt/miniconda3/envs/te/lib/python3.6/site-packages/netplotlib/netplotlib.py in draw(self, show, savePath)
>     435                              fontsize=self.fontsize, horizontalalignment='center',
>     436                              verticalalignment='center', color=self.labelColor)
> --> 437             Var.G.node[n]['patch'] = c
>     438 
>     439         # add edges to the figure
> 
> AttributeError: 'DiGraph' object has no attribute 'node'

I have attached my conda environment packages. I am at python 3.6, networkx 2.4 and netplotlib 1.0.11.
[conda_packages.txt](https://github.com/kirichoi/netplotlib/files/3836546/conda_packages.txt)

**Comment by kirichoi** [comment]
Thanks for reporting this issue. The most recent release of networkx deprecated some functions and caused this problem. I made a new release to address this.

**Comment by kaisengit** [comment]
Now that was extremely fast! Thank you so much, it is working perfectly for me now!
